name: Build/release-ubuntu-24.04-arm

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Install FPM
        run: |
          sudo apt update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev liblzma-dev
          sudo gem install --no-document fpm

      - name: Set environment variable USE_SYSTEM_FPM
        run: echo "USE_SYSTEM_FPM=true" >> $GITHUB_ENV

      - name: Set environment variable USE_HARD_LINKS
        run: echo "USE_HARD_LINKS=false" >> $GITHUB_ENV

      - name: Modify package.json for Linux arm64 build
        run: |
          jq '.build.linux.target = [
            {
              "target": "deb",
              "arch": ["arm64"]
            },
            {
              "target": "AppImage", 
              "arch": ["arm64"]
            }
          ]' package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Modify package.json for dev branch
        if: github.ref == 'refs/heads/dev'
        run: |
          sed -i 's/"productName": "Koodo Reader"/"productName": "Koodo Reader DEV"/' package.json

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          build_script_name: "build"
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Upload DEB arm64
        uses: actions/upload-artifact@v4
        with:
          name: Koodo-Reader-Linux-arm64-DEB
          path: dist/*arm64*.deb

      - name: Upload AppImage arm64
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Koodo-Reader-Linux-arm64-AppImage
          path: dist/*arm64*.AppImage
